export const GET_BY_ID_PENDANAAN_REQUEST = 'GET_BY_ID_PENDANAAN_REQUEST'
export const GET_BY_ID_PENDANAAN_SUCCESS = 'GET_BY_ID_PENDANAAN_SUCCESS'
export const GET_BY_ID_PENDANAAN_ERROR = 'GET_BY_ID_PENDANAAN_ERROR'
