export const READ_SET_PENDANAAN = 'READ_SET_PENDANAAN'
export const READ_ERROR_PENDANAAN = 'READ_ERROR_PENDANAAN'
export const READ_START_LOADING_PENDANAAN = 'READ_START_LOADING_PENDANAAN'
export const READ_STOP_LOADING_PENDANAAN = 'READ_STOP_LOADING_PENDANAAN'
