// READ
export const READ_SET_HASIL_PENGAJUAN = 'READ_SET_HASIL_PENGAJUAN'
export const READ_ERROR_HASIL_PENGAJUAN = 'READ_ERROR_HASIL_PENGAJUAN'
export const READ_START_LOADING_HASIL_PENGAJUAN = 'READ_START_LOADING_HASIL_PENGAJUAN'
export const READ_STOP_LOADING_HASIL_PENGAJUAN = 'READ_STOP_LOADING_HASIL_PENGAJUAN'

// CREATE
export const CREATE_STATUS_HASIL_PENGAJUAN = 'CREATE_STATUS_HASIL_PENGAJUAN'
export const CREATE_KETERANGAN_HASIL_PENGAJUAN = 'CREATE_KETERANGAN_HASIL_PENGAJUAN'
export const CREATE_PETANI_ID_HASIL_PENGAJUAN = 'CREATE_PETANI_ID_HASIL_PENGAJUAN'
export const CREATE_FORM_PENGAJUAN_ID_HASIL_PENGAJUAN = 'CREATE_FORM_PENGAJUAN_ID_HASIL_PENGAJUAN'

// UPDATE
export const UPDATE_HASIL_PENGAJUAN_STATUS = 'UPDATE_HASIL_PENGAJUAN_STATUS'
export const UPDATE_HASIL_PENGAJUAN_KETERANGAN = 'UPDATE_HASIL_PENGAJUAN_KETERANGAN'
export const UPDATE_HASIL_PENGAJUAN_PETANI_ID = 'UPDATE_HASIL_PENGAJUAN_PETANI_ID'
export const UPDATE_HASIL_PENGAJUAN_FORMULIR_PENGAJUAN_ID = 'UPDATE_HASIL_PENGAJUAN_FORMULIR_PENGAJUAN_ID'
