export const READ_SET_HASIL_PENGAJUAN = 'READ_SET_HASIL_PENGAJUAN'
export const READ_ERROR_HASIL_PENGAJUAN = 'READ_ERROR_HASIL_PENGAJUAN'
export const READ_START_LOADING_HASIL_PENGAJUAN = 'READ_START_LOADING_HASIL_PENGAJUAN'
export const READ_STOP_LOADING_HASIL_PENGAJUAN = 'READ_STOP_LOADING_HASIL_PENGAJUAN'
