export const READ_SET_KATEGORI = 'READ_SET_KATEGORI'
export const READ_ERROR_KATEGORI = 'READ_ERROR_KATEGORI'
export const READ_START_LOADING_KATEGORI = 'READ_START_LOADING_KATEGORI'
export const READ_STOP_LOADING_KATEGORI = 'READ_STOP_LOADING_KATEGORI'
