export const READ_SET_PETANI = 'READ_SET_PETANI'
export const READ_ERROR_PETANI = 'READ_ERROR_PETANI'
export const READ_START_LOADING_PETANI = 'READ_START_LOADING_PETANI'
export const READ_STOP_LOADING_PETANI = 'READ_STOP_LOADING_PETANI'
