export const USER_SET_EMAIL = 'USER_SET_EMAIL',
	USER_SET_PASSWORD = 'USER_SET_REGISTER',
	USER_SET_FULLNAME = 'USER_SET_FULLNAME',
	USER_REGISTER_RESET_FORM = 'USER_REGISTER_RESET_FORM',
	USER_SET_ROLE = 'USER_SET_ROLE',
	USER_SET_AUTH = 'USER_SET_AUTH'
